(function(){function Q(a,b){function c(){}c.prototype=a;var d=new c,f;for(f in b)d[f]=b[f];b.toString!==Object.prototype.toString&&(d.toString=b.toString);return d}function L(a,b){for(var c="undefined"!=typeof window?window:exports,d=b.split("."),f=0;f<d.length-1;++f){var g=d[f];"undefined"==typeof c[g]&&(c[g]={});c=c[g]}c[d[d.length-1]]=a}var x=function(){};x.__name__=!0;x.encode=function(a){var b="",c,d,f,g,k,e,l=0;for(a=x._utf8_encode(a);l<a.length;)c=a.charCodeAt(l++),d=a.charCodeAt(l++),f=a.charCodeAt(l++),
g=c>>2,c=(c&3)<<4|d>>4,k=(d&15)<<2|f>>6,e=f&63,Math.isNaN(d)?k=e=64:Math.isNaN(f)&&(e=64),b=b+x._keyStr.split("")[g]+x._keyStr.split("")[c]+x._keyStr.split("")[k]+x._keyStr.split("")[e];return b};x._utf8_encode=function(a){a=l.replace(a,"\r\n","\n");for(var b="",c=0,d=a.length;c<d;){var f=c++,f=a.charCodeAt(f);128>f?b+=String.fromCharCode(f):(127<f&&2048>f?b+=String.fromCharCode(f>>6|192):(b+=String.fromCharCode(f>>12|224),b+=String.fromCharCode(f>>6&63|128)),b+=String.fromCharCode(f&63|128))}return b};
x._utf8_decode=function(a){for(var b="",c=0,d=0,f=0,g=0;c<a.length;)d=a.charCodeAt(c),128>d?(b+=String.fromCharCode(d),c++):191<d&&224>d?(f=a.charCodeAt(c+1),b+=String.fromCharCode((d&31)<<6|f&63),c+=2):(f=a.charCodeAt(c+1),g=a.charCodeAt(c+2),b+=String.fromCharCode((d&15)<<12|(f&63)<<6|g&63),c+=3);return b};var M=function(){};L(M,"Builtins");M.__name__=!0;M.bind=function(a){a.register("center",function(a){var c=[],d=a[0];a=[];"text"==d?a=[["text-align","center"]]:"block"==d&&(a=[["display","block"],
["margin-left","auto"],["margin-right","auto"]]);for(d=0;d<a.length;){var f=a[d];++d;var g=new n("prop_assignment");g.setName(f[0]);g.setValue(f[1]);c.push(g)}return c})};var N=function(){};N.__name__=!0;N.hexToRgb=function(a,b,c){a=l.hex(a,2);b=l.hex(b,2);c=l.hex(c,2);return"#"+a+b+c};var A=function(a,b){b=b.split("u").join("");this.r=RegExp(a,b)};A.__name__=!0;A.prototype={match:function(a){this.r.global&&(this.r.lastIndex=0);this.r.m=this.r.exec(a);this.r.s=a;return null!=this.r.m},__class__:A};
var y=function(){};L(y,"FileModule");y.__name__=!0;y.joinPaths=function(a){for(var b="",c=0,d=a.length;c<d;){var f=c++,b=b+l.replace(a[f],"\\","/");"/"!=b.substring(b.length-2,b.length-1)&&f!=a.length-1&&(b+="/")}return b};y.getExtension=function(a){return a.substring(a.lastIndexOf("."),a.length)};y.getDirectoryName=function(a){a=l.replace(a,"\\","/");return a.substring(0,a.lastIndexOf("/")+1)};y.getContent=function(a){return""};y.Exists=function(a){return!0};y.toDataURL=function(a,b){var c=x.encode(a);
return"data:"+b+";base64,"+c};y.getMimeType=function(a){var b=new F(".jpg .jpeg .png .bmp .gif .svg".split(" "),"image/jpeg image/jpeg image/png image/bmp image/gif image/svg+xml".split(" "));a=y.getExtension(a);return null!=b.get(a)?b.get(a):"applicaton/octet-stream"};var R=function(){var a={},b;b="undefined"!=typeof window?"web":module&&"exports"in module?"node":void 0;if("web"===b)a.Exists=function(a){var b=!1;if(!a||"string"!==typeof a)throw"TypeError:  FileModule.Exists only supports strings.";
var c=new XMHttpRequest;c.open("GET",a,!1);c.send(null);200===c.status&&(b=!0);return b},a.getContent=function(a){if(!a||"string"!==typeof a)throw"TypeError: FileModule.getContent only supports string paths.";var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);if(200!==b.status)throw Error(b.statusText);return b.responseText};else if("node"==b){var c=require("fs");a.Exists=function(a){return c.existsSync(a)};a.getContent=function(a){return c.readFileSync(a)}}return a}(),v=function(){};v.__name__=
!0;v.log=function(a){};var G=function(a,b,c){null==c&&(c=!1);null==a&&(a=function(a){return""});this.doExport=c;this.variables=new F;this.mixins=new F;this.functions=new F;this.helpers=new F;this.getFile=a;this.__dir__=b};L(G,"GSS");G.__name__=!0;G.prototype={gss_import:function(a){var b=this.getFile(a)+"";v.log("Got Import");a=new G(this.getFile,null,!0);K.bind(a);M.bind(a);b=a.lex(b);v.log("Tokenized Import");b=a.parse(b);v.log("Parsed Import");a.interpret(b);v.log("Interpreted Import");for(var b=
0,c=a.variables.keys;b<c.length;){var d=c[b];++b;this.variables.set(d,a.variables.get(d))}b=0;for(c=a.mixins.keys;b<c.length;)d=c[b],++b,this.mixins.set(d,a.mixins.get(d));b=0;for(c=a.functions.keys;b<c.length;)d=c[b],++b,this.functions.set(d,a.functions.get(d))},interpret:function(a){for(var b=0;b<a.length;){var c=a[b];++b;c.getValue(this.variables,this.mixins)}},compile:function(a){for(var b="/*\nGenerated from GSS code using the GSS -> CSS Compiler, written by Ryan Davis.\n*/\n\n",c=0;c<a.length;){var d=
a[c];++c;"mixin_declaration"==d.type&&d.getValue(this.variables,this.mixins);b+=d.getValue(this.variables,this.mixins)}return b},parse:function(a){for(var b=this,c=[],d=this.mixins,f=0,g,k=function(b){null==b&&(b=1);f+=b;g=a[f]},e=function(b){null==b&&(b=1);return a[f+b]},H=function(a){var e=null;return e=function(a){var f=[],h=0,d=a[h];for(v.log(a);h<a.length;)if(d=a[h],"identifier"==a[h][0]&&";"==a[h+1][1]){var g=new n("mixin_reference");g.setName(d[1]);f.push(g);h+=2}else if("identifier"==d[0]&&
"{"==a[h+1][1]||"identifier"==d[0]&&"identifier"==a[h+1][0]||"identifier"==d[0]&&":"==a[h+1][1]&&"pseudo_class"==a[h+2][0]){for(var g=1,k=d[1];"identifier"==a[h+g][0]||":"==a[h+g][1]||"pseudo_class"==a[h+g][0];)":"!=a[h+g][1]&&":"!=a[h+g-1][1]&&(k+=" "),k+=a[h+g][1],g++;h+=g;g=new n("selector");g.setValue(k);if("{"==a[h][1]){for(var k=1,d=[],m=1;0<m;)"{"==a[h+k][1]?m++:"}"==a[h+k][1]&&m--,"}"==a[h+k][1]&&0==m||d.push(a[h+k]),k++;m=e(d);for(d=0;d<m.length;){var s=m[d];++d;g.appendChild(s)}h+=k;f.push(g)}else throw v.log(a[h]),
"SyntaxError:  Unexpected Selector String.";}else if("keyword"==d[0]&&"when"==d[1]&&"keyword"==a[h+1][0]){g=new n("when_pseudo");k=void 0;k=new C.ds.StringMap;k.set("active","active");k.set("hovered","hover");g.setName(k.get(a[h+1][1]));h+=2;k=1;d=[];for(m=1;0<m;)"{"==a[h+k][1]?m++:"}"==a[h+k][1]&&m--,"}"==a[h+k][1]&&0==m||d.push(a[h+k]),k++;h+=k;m=e(d);for(d=0;d<m.length;)s=m[d],++d,g.appendChild(s);f.push(g)}else if("identifier"==d[0]&&":"==a[h+1][1]&&"identifier"==a[h+2][0]){g="normal";"("==a[h+
3][1]&&(g="helper_call");m="";k=0;if("normal"==g)for(k=3,m=a[h+2][1];";"!=a[h+k][1];)m+=" "+a[h+k][1],k++;else{g=4;m=[];for(s=a[h+2][1];")"!=a[h+g][1];)","!=a[h+g][1]&&m.push(l.ltrim(l.rtrim(a[h+g][1]))),g++;h+=g+1;m=null!=b.helpers.get(s)?b.helpers.get(s).__call__(m):""+s+"("+m.join(",")+")"}g=new n("prop_assignment");g.setName(d[1]);g.setValue(m);f.push(g);h+=k+1}else if("identifier"==a[h][0]&&"("==a[h+1][1]){g=2;m=[];for(s=a[h][1];")"!=a[h+g][1];)","!=a[h+g][1]&&m.push(l.ltrim(l.rtrim(a[h+g][1]))),
g++;h+=g+2;if(null!=b.functions.get(s))for(k=b.functions.get(s).__call__(m),d=0;d<k.length;)g=k[d],++d,f.push(g);else throw v.log(b.functions.keys),"ReferenceError: "+s+" is either not defined, or not a valid function.";}else throw v.log(c),"Unexpected Token "+D.string(d)+".";return f}}(this),E=function(a,f){var p=a[0],t=a[1];if("identifier"==p&&"{"==e()[1]||"identifier"==p&&"identifier"==e()[0]){for(var h=1;"identifier"==e(h)[0]||":"==e(h)[1];)":"!=e(h)[1]&&":"!=e(h-1)[1]&&(t+=" "),t+=e(h)[1],h++;
p=new n("selector");p.setValue(t);k(h);if("{"==g[1]){for(var r=1,q=1,w=[];0<r;)"{"==e(q)[1]?r++:"}"==e(q)[1]&&r--,"}"==e(q)[1]&&0==r||w.push(e(q)),q++;k(q);for(var m=H(w),h=0;h<m.length;){var s=m[h];++h;p.appendChild(s)}}return p}if("symbol"==p&&"{"==t&&null!=f){h=0;m=[];t=1;for(q=0;t!=q;)if("{"==e(h)[1]?t++:"}"==e(h)[1]&&q++,r=e(h),"identifier"==r[0]&&":"==e(h+1)[1]&&"identifier"==e(h+2)[0]){p=new n("prop_assignment");p.setName(r[1]);r=e(h+2)[1];for(w=3;";"!=e(h+w)[1];)r+=" "+e(h+w)[1],w++;p.setValue(r);
f.appendChild(p);h+=w+1}else"identifier"==e(h)[0]&&";"==e(h+1)[1]?(p=new n("mixin_reference"),p.setName(r[1]),f.appendChild(p),h+=2):h++;k(h+1);return f}if("identifier"==p&&":"==e()[1]&&"identifier"==e(2)[0]&&";"==e(3)[1]){if("@"==t.split("")[0])return t=t.substring(1,t.length),r=e(2)[1],p=new n("var_assignment"),p.setName(t),p.setValue(r),k(4),p;throw"Unexpected Property Assignment: ["+t+" : "+e(2)[1]+"]";}if("keyword"==p&&"mixin"==t&&"identifier"==e()[0]){if("normal"==("("==e(2)[1]?"parametric":
"normal")){var p=new n("mixin_declaration"),E="",t=e()[1];p.setName(t);var u=!1,q=[];"keyword"==e(2)[0]&&"extends"==e(2)[1]&&(u=!0,"identifier"==e(3)[0]?(E="single",q.push(e(3)[1])):"("==e(3)[1]&&(E="multiple"));if("multiple"==E){for(h=4;")"!=e(h)[1];)r=l.ltrim(l.rtrim(e(h)[1])),","!=e(h)[1]&&(v.log(r),q.push(r)),h++;k(h)}r=1;w=[];for(h=u?"multiple"==E?2:5:3;0<r;)v.log(e(h)),"{"==e(h)[1]?r++:"}"==e(h)[1]&&r--,"}"==e(h)[1]&&0==r||w.push(e(h)),h++;k(h);m=H(w);if(u)for(h=0;h<q.length;)if(r=q[h],++h,
null!=d.get(r))for(r=d.get(r).getChildren(),w=function(a){a=[];for(var b=0;b<m.length;){var c=m[b];++b;a.push(c.name)}return a}(this),E=0,u=r.length;E<u;){for(var s=E++,s=r[s],y=s.name,z=!1,x=0;x<w.length;){var F=w[x];++x;F==y&&(z=!0)}z||m.push(s)}for(h=0;h<m.length;)s=m[h],++h,p.appendChild(s);d.set(t,p)}else{var B=[],t=e()[1];v.log("That shit is a function!");for(h=3;")"!=e(h)[1];)","!=e(h)[1]&&B.push(l.ltrim(l.rtrim(e(h)[1]))),h++;k(h);r=1;w=[];for(q=2;0<r;)"{"==e(q)[1]?r++:"}"==e(q)[1]&&r--,"}"==
e(q)[1]&&0==r||w.push(e(q)),q++;k(q);var C=H(w),G=function(a){v.log('Lexing "'+a+'" as Property Value');var c=a.split(""),d=0,f=c[d];a=[];for(var e=function(a){null==a&&(a=1);d+=a;f=c[d]},h=function(a){return c[d+a]};d<c.length;)if(f=c[d],b.isWhiteSpace(f))e();else if(b.isIdentifier(f)){for(var g=1,k=f;null!=h(g)&&"["!=h(g)&&b.isIdentifier(h(g));)k+=h(g),g++;if("["==h(g)&&"arguments"==k){for(;"]"!=h(g)&&null!=h(g);)b.isWhiteSpace(h(g))||(k+=h(g)),g++;k+=h(g)}else if("("==h(g)&&"arguments"==k)for(;")"!=
h(g)&&null!=h(g);)b.isWhiteSpace(h(g))||(k+=h(g)),g++;e(g+1);a.push(k)}return a},p=new I(function(a){for(var b=0,c=a.length;b<c;){b++;for(var d=0,f=C.length;d<f;){for(var h=d++,h=C[h],e=h.value,g=0,k=B.length;g<k;)var m=g++,e=l.replace(e,B[m],a[m]);g=a;k=G(e);e=k.join(" ");v.log("THESE WERE THE SHIT COCKS I GOT:");v.log(k);for(var m=new A("arguments","g"),p=new A("arguments(\\[(.+)\\])","g"),r=new A("arguments\\[([0-9]+)?->([0-9]+)?\\]","g"),t=new A("arguments\\(([\"'A-Z0-9]+)\\)","g"),n=0,E=k.length;n<
E;){var q=n++,q=k[q];if(r.match(q)){v.log("THIS APPEARS TO BE AN ARGUMENT SUBSET EXPRESSION");v.log(q);var s=l.replace(q,"arguments[",""),s=l.replace(s,"]",""),s=l.replace(s," ",""),u;u=void 0;u=[];for(var H=0,s=s.split("->");H<s.length;){var w=s[H];++H;u.push(D.parseInt(w))}2==u.length&&0==u[1]&&(u[1]=g.length-1);e=l.replace(e,q,g.slice(u[0],u[1]).join(" "))}else t.match(q)?(u=l.replace(q,"arguments(",""),u=l.replace(q,")",""),e=l.replace(e,q,g.join(u))):p.match(q)?(u=l.replace(q,"arguments[",""),
u=l.replace(u,"]",""),u=D.parseInt(u),e=l.replace(e,q,g[u])):m.match(q)&&(e=l.replace(e,q,g.join(" ")))}h.setValue(e)}}return C});b.functions.set(t,p)}return p}if("keyword"==p&&"import"==t&&"string"==e()[0])return p=e()[1],b.gss_import(p),k(3),p=new n("import");if("stream_comment"==p)return p=new n("comment"),p.setValue(t),k(),p;if("block_comment"==p)return k(),new n("block_comment");v.log(c);throw"Unrecognized token "+D.string(a)+".";};f<a.length;){g=a[f];var u=E(g);c.push(u)}return c},lex:function(a){var b=
a.split(""),c=[],d=0,f;a=function(a,b){c.push([a,b])};for(var g=function(a){null==a&&(a=1);d+=a;f=b[d]},k=function(a){null==a&&(a=1);return b[d+a]};d<b.length;)if(f=b[d],this.isWhiteSpace(f)){for(var e=1;this.isWhiteSpace(k(e));)e++;g(e)}else if(this.isSymbol(f))a("symbol",f),g();else if((new A("[\"']","")).match(f)){for(var l=f,e=1,n="";k(e)!=l;)n+=k(e),e++;g(e+1);a("string",n)}else if("/"==f&&"/"==k()){l="";for(e=2;!this.isLineBreaker(k(e));)l+=k(e),e++,v.log(k(e));g(e);a("block_comment",l)}else if("/"==
f&&"*"==k()){l="";for(e=2;"*"!=k(e)||"/"!=k(e+1);)l+=k(e),e++;g(e+2);a("stream_comment",l)}else if(this.isIdentifier(f)){n=f;for(e=1;this.isIdentifier(k(e));)n+=k(e),e++;this.isKeyword(n)?a("keyword",n):this.isPseudoClassName(n)?a("pseudo_class",n):a("identifier",n);g(e)}else throw"LexError: Unexpected "+f+".";return c},isPseudoClassName:function(a){for(var b="active first-letter first-line focused hover link visited".split(" "),c=!1,d=0;d<b.length;){var f=b[d];++d;if(f==a){c=!0;break}}return c},
isIdentifier:function(a){return!this.isWhiteSpace(a)&&!this.isSymbol(a)},isDigit:function(a){return(new A("[0-9]","")).match(a)},isLineBreaker:function(a){return(new A("[\n\r]","")).match(a)},isWhiteSpace:function(a){return(new A("\\s","")).match(a)},isKeyword:function(a){return(new A("mixin|extends|import|when|hovered|active","")).match(a)},isSymbol:function(a){return(new A("[\\{\\}\\(\\):;,]","")).match(a)},set:function(a,b,c){if(null!=O.getProperty(this,a+"s"))switch(a){case "variable":this.variables.set(b,
c);break;case "function":this.functions.set(b,new I(c));break;case "helper":this.helpers.set(b,new J(c));break;default:v.log("Anal Testicles")}else throw"GSS object has no field "+a+"s.";},helper:function(a,b){var c=new J(b);this.helpers.set(a,c)},register:function(a,b){var c=new I(b);this.functions.set(a,c)},__class__:G};var n=function(a){this.indents=4;this.type=a;this.childNodes=[];this.toAppendAfter=[];this.hasParent=!1};n.__name__=!0;n.prototype={getChildren:function(){return this.childNodes},
getValue:function(a,b){var c=function(a){var b=null;return b=function(a){var c=[];if("selector"==a.type||"when_pseudo"==a.type)c.push(a.value),a.hasParent&&c.push(b(a.parent));c.reverse();return c.join(" ")}}(this);if("selector"==this.type){for(var d=c(this),f=""+d+" {\n",g=0,k=this.childNodes;g<k.length;){var e=k[g];++g;if("prop_assignment"==e.type||"mixin_reference"==e.type){if("mixin_reference"==e.type)for(d=0,c=e.childNodes;d<c.length;){var n=c[d];++d;n.setParent(this)}f+=e.getValue(a,b);f+="\n"}else"selector"!=
e.type&&"when_pseudo"!=e.type||this.toAppendAfter.push(e.getValue(a,b))}f+="}\n";g=0;for(k=this.toAppendAfter;g<k.length;)e=k[g],++g,f+=e;return f}if("prop_assignment"==this.type){k=this.getPrefixes(this.name.substring(1));g="normal";"~"==this.name.substring(0,1)&&(g="prefixed");e=f="";"@"==this.value.substring(0,1)?(d=this.value.substring(1,this.value.length),null!=a.get(d)&&(e+=D.string(a.get(d)))):e+=this.value;c=this.getIndentation();if("prefixed"==g)for(d=this.name.substring(1,this.name.length),
f+=c+(""+d+" : "+e+";\n"),g=0;g<k.length;)n=k[g],++g,f+=c+("-"+n+"-"+d+" : "+e+";\n");else f+=c+(""+this.name+" : "+e+";");return f}if("when_pseudo"==this.type){if(this.hasParent){c=c(this)+":"+this.name;d=l.replace(c," null","");d=l.replace(d," :",":");f=""+d+" {\n";g=0;for(k=this.childNodes;g<k.length;)e=k[g],++g,"selector"==e.type?(e=l.replace(e.getValue(a,b),c,d),e=l.replace(e," null",""),e=l.replace(e,this.parent.value,this.parent.value+":"+this.name),this.toAppendAfter.push(e)):(f+=e.getValue(a,
b),f+="\n");f+="}\n";g=0;for(k=this.toAppendAfter;g<k.length;)e=k[g],++g,f+=e;return f}return""}if("var_assignment"==this.type)return a.set(this.name,this.value),"";if("mixin_declaration"==this.type)return b.set(this.name,this),"";if("mixin_reference"==this.type){if(null!=b.get(this.name)){k=b.get(this.name);f="";g=0;for(k=k.childNodes;g<k.length;)e=k[g],++g,"selector"==e.type||"when_pseudo"==e.type?(d=c(this.parent),console.log("THIS IS THE SELECTOR:"),console.log(d),e=e.getValue(a,b),console.log(e),
this.parent.toAppendAfter.push(d+e)):(f+=e.getValue(a,b),f+="\n");return f}throw"ReferenceError:  "+this.name+" is either not defined, or not a valid mixin.";}return"comment"==this.type?"/*\n"+this.value+"\n*/":"string"==this.type?'"'+this.value+'"':""},getPrefixes:function(a){var b=new C.ds.StringMap;b.set("align-content",["webkit"]);b.set("align-items",["webkit"]);b.set("align-self",["webkit"]);b.set("animation",["webkit"]);b.set("background-size",["webkit"]);b.set("border-image",["webkit","o"]);
b.set("border-radius",["webkit"]);b.set("linear-gradient",["webkit"]);return null!=b.get(a)?b.get(a):["webkit","moz","o","ms"]},setValue:function(a){this.value=a},setName:function(a){this.name=a},setParent:function(a){this.parent=a;this.hasParent||(this.hasParent=!0)},appendChild:function(a){this.childNodes.push(a);a.setParent(this)},getIndentation:function(){var a=0;this.hasParent&&(a+=this.indents);for(var b="",c=0;c<a;)c++,b+=" ";return b},__class__:n};var I=function(a){n.call(this,"function");
this.func=a};I.__name__=!0;I.__super__=n;I.prototype=Q(n.prototype,{__call__:function(a){return this.func(a)},__class__:I});var J=function(a){n.call(this,"helper_function");this.func=a};J.__name__=!0;J.__super__=n;J.prototype=Q(n.prototype,{__call__:function(a){return this.func(a)},__class__:J});var K=function(){};L(K,"Helpers");K.__name__=!0;K.bind=function(a){a.helper("rgb",function(a){var c=D.parseInt(a[0]),d=D.parseInt(a[1]);a=D.parseInt(a[1]);return N.hexToRgb(c,d,a)});a.helper("url",function(b){b=
b[0];var c=a.__dir__.split("/");y.joinPaths([c.slice(0,c.length-1).join("/"),b]);return'url("'+b+'")'});a.helper("format",function(a){var c=a[0];a=a.slice(1,a.length);for(var d=0,f=a.length;d<f;)var g=d++,c=l.replace(c,"{"+g+"}",a[g]);return c})};var B=function(){};B.__name__=!0;B.cca=function(a,b){var c=a.charCodeAt(b);return c!=c?void 0:c};B.substr=function(a,b,c){if(null!=b&&0!=b&&null!=c&&0>c)return"";null==c&&(c=a.length);0>b?(b=a.length+b,0>b&&(b=0)):0>c&&(c=a.length+c-b);return a.substr(b,
c)};var P=function(){};P.__name__=!0;P.main=function(){G;K;console.log("GSS Ready");y.getContent=R.getContent;y.Exists=R.Exists};var S=function(){};S.__name__=!0;var F=function(a,b){this.keys=[];this.values=[];if(null!=a&&null!=b&&a.length==b.length)for(var c=0,d=a.length;c<d;){var f=c++;this.keys.push(a[f]);this.values.push(b[f])}};F.__name__=!0;F.prototype={extend:function(a){for(var b=0,c=a.keys;b<c.length;){var d=c[b];++b;this.set(d,a.get(d))}},get:function(a){for(var b=null,c=0,d=this.keys.length;c<
d;){var f=c++;if(this.keys[f]==a){b=this.values[f];break}}return b},set:function(a,b){if(null!=this.get(a))for(var c=0,d=this.keys.length;c<d;){var f=c++;this.keys[f]==a&&(this.values[f]=b)}else this.keys.push(a),this.values.push(b)},__class__:F};var O=function(){};O.__name__=!0;O.getProperty=function(a,b){var c;return null==a?null:a.__properties__&&(c=a.__properties__["get_"+b])?a[c]():a[b]};var D=function(){};D.__name__=!0;D.string=function(a){return z.Boot.__string_rec(a,"")};D.parseInt=function(a){var b=
parseInt(a,10);0!=b||120!=B.cca(a,1)&&88!=B.cca(a,1)||(b=parseInt(a));return isNaN(b)?null:b};var l=function(){};l.__name__=!0;l.isSpace=function(a,b){var c=B.cca(a,b);return 8<c&&14>c||32==c};l.ltrim=function(a){for(var b=a.length,c=0;c<b&&l.isSpace(a,c);)c++;return 0<c?B.substr(a,c,b-c):a};l.rtrim=function(a){for(var b=a.length,c=0;c<b&&l.isSpace(a,b-c-1);)c++;return 0<c?B.substr(a,0,b-c):a};l.replace=function(a,b,c){return a.split(b).join(c)};l.hex=function(a,b){var c="";do c="0123456789ABCDEF".charAt(a&
15)+c,a>>>=4;while(0<a);if(null!=b)for(;c.length<b;)c="0"+c;return c};var C={ds:{}};C.ds.StringMap=function(){this.h={}};C.ds.StringMap.__name__=!0;C.ds.StringMap.__interfaces__=[S];C.ds.StringMap.prototype={get:function(a){return this.h["$"+a]},set:function(a,b){this.h["$"+a]=b},__class__:C.ds.StringMap};var z={Boot:function(){}};z.Boot.__name__=!0;z.Boot.__string_rec=function(a,b){if(null==a)return"null";if(5<=b.length)return"<...>";var c=typeof a;"function"==c&&(a.__name__||a.__ename__)&&(c="object");
switch(c){case "object":if(a instanceof Array){if(a.__enum__){if(2==a.length)return a[0];c=a[0]+"(";b+="\t";for(var d=2,f=a.length;d<f;)var g=d++,c=2!=g?c+(","+z.Boot.__string_rec(a[g],b)):c+z.Boot.__string_rec(a[g],b);return c+")"}d=a.length;c="[";b+="\t";for(f=0;f<d;)g=f++,c+=(0<g?",":"")+z.Boot.__string_rec(a[g],b);return c+"]"}try{f=a.toString}catch(k){return"???"}if(null!=f&&f!=Object.toString&&(c=a.toString(),"[object Object]"!=c))return c;f=null;c="{\n";b+="\t";d=null!=a.hasOwnProperty;for(f in a)d&&
!a.hasOwnProperty(f)||("prototype"==f||"__class__"==f||"__super__"==f||"__interfaces__"==f||"__properties__"==f)||(2!=c.length&&(c+=", \n"),c+=b+f+" : "+z.Boot.__string_rec(a[f],b));b=b.substring(1);return c+="\n"+b+"}";case "function":return"<function>";case "string":return a;default:return String(a)}};z.Boot.__interfLoop=function(a,b){if(null==a)return!1;if(a==b)return!0;var c=a.__interfaces__;if(null!=c)for(var d=0,f=c.length;d<f;){var g=d++,g=c[g];if(g==b||z.Boot.__interfLoop(g,b))return!0}return z.Boot.__interfLoop(a.__super__,
b)};z.Boot.__instanceof=function(a,b){if(null==b)return!1;switch(b){case V:return(a|0)===a;case T:return"number"==typeof a;case U:return"boolean"==typeof a;case String:return"string"==typeof a;case W:return!0;default:if(null!=a){if("function"==typeof b){if(a instanceof b)return b==Array?null==a.__enum__:!0;if(z.Boot.__interfLoop(a.__class__,b))return!0}}else return!1;return b==X&&null!=a.__name__||b==Y&&null!=a.__ename__?!0:a.__enum__==b}};Math.__name__=["Math"];Math.NaN=Number.NaN;Math.NEGATIVE_INFINITY=
Number.NEGATIVE_INFINITY;Math.POSITIVE_INFINITY=Number.POSITIVE_INFINITY;Math.isFinite=function(a){return isFinite(a)};Math.isNaN=function(a){return isNaN(a)};String.prototype.__class__=String;String.__name__=!0;Array.prototype.__class__=Array;Array.__name__=!0;var V={__name__:["Int"]},W={__name__:["Dynamic"]},T=Number;T.__name__=["Float"];var U=Boolean;U.__ename__=["Bool"];var X={__name__:["Class"]},Y={};x._keyStr="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=";P.main()})();
